server:
    port: 8080

spring:
    application:
        name: rental-app
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rentaly_db}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            properties:
                hibernate.format_sql: true
    flyway:
        enabled: false
        locations: classpath:/db/migration
        baseline-on-migrate: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 20MB
            file-size-threshold: 2KB
            location: /tmp
    
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY:8bdfb0e404960aaa8573c43bcdb330c4e7dcac924592a91ed1a0c3fa6222095e}
            expiration: ${JWT_EXPRATION:900000}
            refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
    
    jackson:
        serialization:
            write-dates-as-timestamps: false
        date-format: yyyy-MM-dd'T'HH:mm:ss

springdoc:
    api-docs:
        path: /api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
