CREATE TYPE "roles" AS ENUM (
  'admin',
  'user'
);

CREATE TYPE "car_type" AS ENUM (
  'sedan',
  'suv',
  'truck'
);

CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'cancelled');
CREATE TYPE rent_status AS ENUM ('rented', 'returned', 'not_rented', 'cancelled');

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "password" varchar,
  "role" roles,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "price" int,
  "car_type" car_type,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "car_inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_id" int,
  "quantity" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "invoices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "car_id" int,
  "total_price" int,
  "start_date" timestamp,
  "end_date" timestamp,
  "returned_at" timestamp,
  "payment_status" payment_status,
  "rent_status" rent_status,
  "created_at" timestamp,
  "updated_at" timestamp
);

create table if not exists car_images (
    id serial primary key,
    car_id bigint not null,
    image_url varchar(255) not null default './images/default.png',
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

alter table if exists car_images add constraint fk_car_images_car_id foreign key (car_id) references cars(id);

ALTER TABLE "car_inventory" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");
