CREATE TYPE "roles" AS ENUM (
  'admin',
  'user'
);

CREATE TYPE "car_type" AS ENUM (
  'sedan',
  'suv',
  'truck'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "password" varchar,
  "role" roles,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cars" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "price" int,
  "car_type" car_type,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "car_inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_id" int,
  "quantity" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "invoices" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "car_id" int,
  "total_price" int,
  "start_date" timestamp,
  "end_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "car_inventory" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "invoices" ADD FOREIGN KEY ("car_id") REFERENCES "cars" ("id");
